<?php

namespace App\Hizb\Syshab\Models;

use CodeIgniter\Model;

class EmployeeModel extends Model
{
    protected $DBGroup = 'default';
    protected $table = 'H_A101';
    protected $primaryKey = 'id';
    protected $useAutoIncrement = true;
    protected $insertID = 0;
    protected $returnType = 'array';
    protected $useSoftDeletes = false;
    protected $protectFields = true;
    protected $allowedFields = [
        "Nik",
        "Nama",
        "TglMasuk",
        "tglEfektif",
        "EmpType",
        "TglAwalKontrak",
        "TglAkhirKontrak",
        "KontrakKe",
        "TglAwalTetap",
        "Active",
        "TglResign",
        "KdSite",
        "KdDepar",
        "KdJabatan",
        "KdLokasi",
        "KdLevel",
        "KdSubLevel",
        "PointHire",
        "Gender",
        "TmpLahir",
        "TglLahir",
        "Agama",
        "StSipil",
        "StMarital",
        "GolDarah",
        "Alamat",
        "Kota",
        "KdPos",
        "Propinsi",
        "kdtelp",
        "Telp",
        "NoHP",
        "Email",
        "NoKTP",
        "TglExpiredKTP",
        "AlamatID",
        "KotaID",
        "PropinsiID",
        "KdPosID",
        "TypeSIM",
        "NoSIM",
        "TglExpiredSIM",
        "ContactPerson",
        "AlmPerson",
        "TelpPerson",
        "HubPerson",
        "UkuranBaju",
        "UkuranSepatu",
        "UkuranCelana",
        "Foto",
        "NoMutasi",
        "NoPromosi",
        "NoDemosi",
        "FExpatriate",
        "FHousing",
        "FFlexible",
        "FSPL",
        "FHitungOT",
        "FSchedulingShift",
        "Shift",
        "FNotRP",
        "TglTblCuti",
        "TglExpLeave",
        "FHangus",
        "CutiLalu",
        "CutiSkr",
        "CutiCallIn",
        "CutiTahunIni",
        "Jatah",
        "ELeaveDate",
        "ELeaveExpDate",
        "CutiPanjangLalu",
        "CutiPanjang",
        "CutiPanjangDiambil",
        "SisaCutiPanjang",
        "TglInitPL",
        "PLeaveDate",
        "PLeaveExpDate",
        "PLeaveStatus",
        "PLeaveReturnDate",
        "PLeavePrevBalance",
        "PLeaveEmerge",
        "PLeaveClaimed",
        "PLeaveRemaining",
        "ClaimPercentage",
        "PeriodeTimbulClaim",
        "PeriodeLastClaimFrame",
        "PeriodeLastClaimLens",
        "OutpatientMax",
        "OutpatientClaim",
        "OutpatientSisa",
        "InpatientMax",
        "InpatientClaim",
        "InpatientSisa",
        "GlassesMonoNormalMax",
        "GlassesMonoNormalClaim",
        "GlassesMonoNormalSisa",
        "GlassesMonoSilinderMax",
        "GlassesMonoSilinderClaim",
        "GlassesMonoSilinderSisa",
        "GlassesBiNormalMax",
        "GlassesBiNormalClaim",
        "GlassesBiNormalSisa",
        "GlassesBiSilinderMax",
        "GlassesBiSilinderClaim",
        "GlassesBiSilinderSisa",
        "GlassesFrameMax",
        "GlassesFrameClaim",
        "GlassesFrameSisa",
        "MaternityMax",
        "MaternityClaim",
        "MaternitySisa",
        "nMaternity",
        "CreatedBy",
        "CreatedIn",
        "CreatedTime",
        "ModifiedBy",
        "ModifiedIn",
        "ModifiedTime",
        "StEdit",
        "DeleteBy",
        "DeleteTime",
        "FCover",
        "FKirim",
        "KdSubLevelRit",
        "NoMutasiPre",
        "NoPromosiPre",
        "TglActiveR",
        "TglActiveCP",
        "TRoster",
        "TCtP",
        "SendEmail",
        "TglDutyStart",
        "TglDutyEnd",
        "KdCompany",
        "NoBPJSKes",
        "ttcperiodik",
        "kerjar",
        "liburr",
        "kerjacp",
        "liburcp",
        "kdlok",
        "tnobpjskes",
        "tglJoint"
    ];

    protected $selectFields = "
        Nik,
        Nama,
        TglMasuk,
        tglEfektif,
        EmpType,
        TglAwalKontrak,
        TglAkhirKontrak,
        KontrakKe,
        TglAwalTetap,
        Active,
        TglResign,
        KdSite,
        KdDepar,
        KdJabatan,
        KdLokasi,
        KdLevel,
        KdSubLevel,
        PointHire,
        Gender,
        TmpLahir,
        TglLahir,
        Agama,
        StSipil,
        StMarital,
        GolDarah,
        Alamat,
        Kota,
        KdPos,
        Propinsi,
        kdtelp,
        Telp,
        NoHP,
        Email,
        NoKTP,
        TglExpiredKTP,
        AlamatID,
        KotaID,
        PropinsiID,
        KdPosID,
        TypeSIM,
        NoSIM,
        TglExpiredSIM,
        ContactPerson,
        AlmPerson,
        TelpPerson,
        HubPerson,
        UkuranBaju,
        UkuranSepatu,
        UkuranCelana,
        Foto,
        NoMutasi,
        NoPromosi,
        NoDemosi,
        FExpatriate,
        FHousing,
        FFlexible,
        FSPL,
        FHitungOT,
        FSchedulingShift,
        Shift,
        FNotRP,
        TglTblCuti,
        TglExpLeave,
        FHangus,
        CutiLalu,
        CutiSkr,
        CutiCallIn,
        CutiTahunIni,
        Jatah,
        ELeaveDate,
        ELeaveExpDate,
        CutiPanjangLalu,
        CutiPanjang,
        CutiPanjangDiambil,
        SisaCutiPanjang,
        TglInitPL,
        PLeaveDate,
        PLeaveExpDate,
        PLeaveStatus,
        PLeaveReturnDate,
        PLeavePrevBalance,
        PLeaveEmerge,
        PLeaveClaimed,
        PLeaveRemaining,
        ClaimPercentage,
        PeriodeTimbulClaim,
        PeriodeLastClaimFrame,
        PeriodeLastClaimLens,
        OutpatientMax,
        OutpatientClaim,
        OutpatientSisa,
        InpatientMax,
        InpatientClaim,
        InpatientSisa,
        GlassesMonoNormalMax,
        GlassesMonoNormalClaim,
        GlassesMonoNormalSisa,
        GlassesMonoSilinderMax,
        GlassesMonoSilinderClaim,
        GlassesMonoSilinderSisa,
        GlassesBiNormalMax,
        GlassesBiNormalClaim,
        GlassesBiNormalSisa,
        GlassesBiSilinderMax,
        GlassesBiSilinderClaim,
        GlassesBiSilinderSisa,
        GlassesFrameMax,
        GlassesFrameClaim,
        GlassesFrameSisa,
        MaternityMax,
        MaternityClaim,
        MaternitySisa,
        nMaternity,
        CreatedBy,
        CreatedIn,
        CreatedTime,
        ModifiedBy,
        ModifiedIn,
        ModifiedTime,
        StEdit,
        DeleteBy,
        DeleteTime,
        FCover,
        FKirim,
        KdSubLevelRit,
        NoMutasiPre,
        NoPromosiPre,
        TglActiveR,
        TglActiveCP,
        TRoster,
        TCtP,
        SendEmail,
        TglDutyStart,
        TglDutyEnd,
        KdCompany,
        NoBPJSKes,
        ttcperiodik,
        kerjar,
        liburr,
        kerjacp,
        liburcp,
        kdlok,
        tnobpjskes,
        tglJoint
    ";

    protected $selectFields2 = "
        a.*,
        b.region_name,
        c.NmSec,
        d.KdSec,
        d.nmJabat AS jabatanxx,
        e.NmLevel,
        f.NmDepar
    ";

    // Dates
    protected $useTimestamps = true;
    protected $dateFormat = 'datetime';
    protected $createdField = 'created_at';
    protected $updatedField = 'updated_at';
    protected $deletedField = 'deleted_at';

    // Validation
    protected $validationRules = [];
    protected $validationMessages = [];
    protected $skipValidation = false;
    protected $cleanValidationRules = true;

    // Callbacks
    protected $allowCallbacks = true;
    protected $beforeInsert = [];
    protected $afterInsert = [];
    protected $beforeUpdate = [];
    protected $afterUpdate = [];
    protected $beforeFind = [];
    protected $afterFind = [];
    protected $beforeDelete = [];
    protected $afterDelete = [];
}